Feature/spaceship ls
Eclyocy/otus-space pull request #14
Opened 2024-07-16 15:05 UTC by egiK1337

Для сервиса корабля добавил сущности базы данных и методы добавления доменных сущностей

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Domain/EfCore/EfCoreContext.cs
Нужно будет вынести параметры, запланировать на следующую итерацию.

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Domain/Implementation/ResourceRepository.cs
Тут нужно вынести CrUD операции в абстрактный класс

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Domain/SpaceShip.Domain.csproj
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets> два раза

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/SpaceShipDTO.cs
Зачем перешли на коллекцию моделей с коллекции DTO?

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
Реализация метода Update не соотвествует чистой архитектуре, зачем мы в сервисе создаем объект модели уровня БД

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.WebAPI/Program.cs
> +if (app.Environment.IsDevelopment())
Чем мешает вызов swagger в продуктивной среде?

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.WebAPI/WebAPI.csproj
> +      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
зачем два раза

2024-07-18 18:34 UTC, dm-demin commented on SpaceShip/src/WebAPI/Controllers/ProblemController.cs
Почему появилось отдельное webapi?

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/mock/MockSpaceShip.Service/IShipService.cs
Удалить этот файл.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/mock/MockSpaceShip.Service/MockSpaceShip.Service.csproj
Откатить изменения в этот файл.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/mock/MockSpaceShip.Service/MockSpaceShipService.cs
Откатить изменения в этот файл.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/WebAPI/appsettings.json
Мы же пользуемся ENV, а не appsettings.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/WebAPI/appsettings.Development.json
Мы же пользуемся ENV, а не appsettings.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/WebAPI/Controllers/ProblemController.cs
Вся директория SpaceShip/src/WebAPI не нужна.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.WebAPI/WebAPI.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
Зачем этот пакет на уровне WebAPI?

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.WebAPI/Program.cs
> +builder.Services
Некрасиво написано (с неверными отступами).

Лучше писать сперва один вид сервисов, затем второй. Сейчас они не сгруппированы. Предлагаю сохранить оригинальный порядок.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.WebAPI/Controllers/ResourceTypeController.cs
В PR для БД вряд ли нужны новые контроллеры.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.WebAPI/Controllers/ResourceController.cs
В PR для БД вряд ли нужны новые контроллеры.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.WebAPI/Controllers/ProblemController.cs
В PR для БД вряд ли нужны новые контроллеры.

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Services/ResourceService.cs
Нужны ли новые сервисы в PR про слой работы с БД?

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Services/ResourceTypeService.cs
Нужны ли новые сервисы в PR про слой работы с БД?

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/EfCore/EfCoreContext.cs
> +                string conn = "Server=127.0.0.1;Port=5432;Database=Spaceship;User Id=postgres;Password=123;";
Почему захардкожено здесь?

2024-07-18 18:34 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/Implementation/ProblemRepository.cs
> +        public bool FindById(int id)
Зачем этот метод? Интересно искать саму сущность.
Так придётся два раза отдавать запросы в БД.
А можно было бы отдавать Problem? (т.е. nullable).

2024-07-18 18:49 UTC, Eclyocy requested changes
Лучше добавить абстрактный класс для репозиториев.
Таким образом, будет один интерфейс базовый (определяет CRUD), несколько интерфейсов для каждого из ресурсов (пустые), один абстрактный класс BaseRepository с реализацией CRUD и несколько реализаций модель-специфичных репозиториев.

Всё можно подсмотреть в GameController.

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/mock/MockSpaceShip.Service/MockSpaceShip.Service.csproj
Зачем удаляется этот файл?

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/mock/MockSpaceShip.Service/MockSpaceShipService.cs
Зачем удаляется этот файл?

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/Implementation/SpaceshipRepository.cs
> +        public bool FindById(Guid id)
Зачем этот метод? (Аналогично существующему комментарию.)

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/Interfaces/IProblemRepository.cs
> +        public Problem Create(string name);
Create должен принимать модель.

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/Interfaces/IProblemRepository.cs
> +        public bool FindById(int id);
Я не вижу пользы от этого метода.

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/Interfaces/IProblemRepository.cs
> +        public Problem Get(int id);
Заменить возвращаемый типа на Problem?.

2024-07-18 18:49 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Domain/Interfaces/IProblemRepository.cs
> +}
Не хватает метода Delete.

2024-08-08 17:46 UTC, dm-demin requested changes
Нужно выносить переменные подключения в env + править docker-compose.yaml, иначе в контейнере не запуститься.

Не очень понял с исключениями. Репозиторий не должен их выбрасывать при проблемах работы с БД?

2024-08-08 17:46 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Domain/Model/BaseEntity.cs
тут на будущее можно добавить дату изменения, флаг удаления записи

2024-08-08 17:46 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
> -        _logger.LogInformation("Create space ship");
Чем логи помешали?

2024-08-08 17:46 UTC, dm-demin commented on SpaceShip/src/SpaceShip.WebAPI/appsettings.json
Нужно вытащить переменные работы с БД в переменные окружения по аналогии с rabbitMQ. Сервис должен запускаться на общем контейнере с pg в docker. Все переменные в общем docker-compose

2024-08-08 17:46 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
> +            throw new NotFoundException($"User with ID {shipId} not found.");
User???

2024-08-08 17:46 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
> +        if (shipRequest.Name != null && shipRequest.Name != currentShip.Name)
Почему только имя? полей же больше. Нужно менять и номер дня, и состояние, раз оно введено.

2024-08-08 17:46 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
> +            _shipRepository.Update(ship);
так может через приватный метод?

2024-08-08 19:30 UTC, dm-demin requested changes

2024-08-08 19:30 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Domain/Model/Ship.cs
> +        public string Name { get; set; }
имя корабле не передаётся в запросе от игрового контроллера, наверное можно сделать поле nullable

2024-08-08 19:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.WebAPI/Program.cs
не вижу uri для swagger

2024-08-18 19:09 UTC, dm-demin approved these changes

2024-08-18 19:10 UTC, Eclyocy approved these changes

2024-08-18 19:12 UTC, merged