Feature/event generator
Eclyocy/otus-space pull request #20
Opened 2024-08-01 16:38 UTC by tmpbx29

2024-08-05 04:27 UTC, dm-demin reviewed
Не понятна структура БД, может картинкой приложить к ответу. Если мои догадки верны, то лучше поправить имена классов.

Написал коммент про editorconfig - есть мелкие придирки про пробелы и пустые строки в конце файлов.

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/.editorconfig
Возьми файлик в игровом контроллере или корабле. Тут как будто многого не хватает. В кое много пробелов лишних, не хватает пустых строк в конце файла и т.п.

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Repository/BaseRepository.cs
Может быть сразу определить CrUD операции, мы же наверное будем подчищать генераторы уже завершенных игровых сессий?

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator.Services/Services/EventService.cs
> +            createEventDto.troublecoint = random.Next(0, 10);
Пока ок, но как на будущее мы хотим начислять коины?

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
кодировку бы поправить

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator/EventGenerator.http
Что это за файл?

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator/Properties/launchSettings.json
> +        //"RABBITMQ__NEWDAYQUEUENAMESHIP": "q_new_day_ship",
зачем тут настройки для корабля, вижу, что закоментировано,  но может быть проще почистить лишнее.

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
НЕ увидел метод создания генератора проблем со схемы, POST /problem-generators

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
> +        public async Task<EventResponse> CreateEvent(Guid shipId)
Это видимо метод создания генератора проблем, но из названия не очень понятно

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator.Services/Models/Event/CreateEventDto.cs
НЕ очень понимаю структуру ответа. Это ответ о создании генератора или конкретного события? Если события, то тут совсем не хватает полей про ресурс и тип проблемы, если это сам генератор, то название это не отражает.

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Ship.cs
Не понимаю структуру, зачем таблица с одним id корабля. Корабли и генераторы же связаны 1 к 1. Тут хотим расширять атрибуты корабля в будущем?

2024-08-05 04:27 UTC, dm-demin commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
Не могу понять структуру БД, но если предположить, что это таблица с генераторами, то становиться чуть понятнее. Видимо имя не отражает содержание. 

Если это именно события-проблемы - то тут нет ссылки на ресурсы и какого-то ключа проблемы. Зачем в ответе о проблеме количество коинов? Типа я вам еще покажу, могу создать крутые проблемы?

2024-08-11 08:55 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Helpers/GuidGenerator.cs
Убрал. Изначально хотел использоват его, но потом перенес генерацию в сам сервис EventGenerator.Services.Services.EventService

2024-08-11 08:56 UTC, tmpbx29 commented on ProblemGenerator/.editorconfig
Забрал. Причесал код в соотвествии с этим .editorconfig

2024-08-11 08:59 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
Он ниже, где кодировка не отображается.

2024-08-11 09:00 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Properties/launchSettings.json
> +        //"RABBITMQ__NEWDAYQUEUENAMESHIP": "q_new_day_ship",
Почистил

2024-08-11 09:00 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
> +        public async Task<EventResponse> CreateEvent(Guid shipId)
Да, это он

2024-08-11 09:01 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/Event/CreateEventDto.cs
Ответ - событие.

2024-08-11 09:05 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Services/EventService.cs
> +            createEventDto.troublecoint = random.Next(0, 10);
Надо обсудить на встрече

2024-08-11 09:08 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Ship.cs
Сюда буду складывать входящие ShipId. по которым пришел запрос на создание события

2024-08-11 09:09 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
Да. это само событие. Надо обсудить на митинге.

2024-08-11 17:29 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Repository/BaseRepository.cs
Пока только Create. Добавлю событие получение всех event по ship_id

2024-09-02 19:57 UTC, tmpbx29 commented
Поравил миграцию и добавил описание

2024-09-11 17:06 UTC, Eclyocy requested changes
Требуется разобраться с routes и ID, а также со счётчиками монет.
Оставила ещё множество мелких замечаний.

2024-09-11 17:06 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
> +    public class Event : BaseEntity
Зачем делать отдельное id, если id уже есть из BaseEntity?

2024-09-11 17:06 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Generator.cs
> +    public class Generator : BaseEntity
Аналогичный вопрос про дублирующее ID.

2024-09-11 17:06 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Models/Event/CreateEventDto.cs
> +        public int EventCoint { get; set; }
Те же замечания, что и в прочих аналогичных местах.

2024-09-11 17:06 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +            Generator generator = _generatorRepository.Get(shipId);
Из-за путаницы с ID это работает не так, как ожидается.

2024-09-11 17:06 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Элементы решения", "Элементы решения", "{D3364EA2-1B82-4683-A5A3-1C44747150EA}"
Переименовать директорию.

2024-09-22 16:16 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        /// Заглушка - Получение Guid корабля.
В рамках нашего проекта, думаю не принципиально, какой язык использовать в комментариях

2024-09-22 16:18 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        [Route("{shipId}")]
Поправил

2024-09-22 16:19 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +    [Route("/api/generator")]
поправил

2024-09-22 16:19 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        /// Создать новое событие.
поправил

2024-09-22 16:20 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        public CreateGeneratorRequest GetShip()
Уберу его в процессе добавления консумера/продюсера

2024-09-22 16:21 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Controllers/EventController.cs
> +    [Route("/api/events")]
Поменял на /api/generators/{generatorId}/events

2024-09-22 16:25 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Mappers/GeneratorMapper.cs
> +    /// Mappings for generatop models.
Исправил

2024-09-22 16:44 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Properties/launchSettings.json
> +        "RABBITMQ__NEWDAYQUEUENAMEGENERATOR": "q_new_day_generator"
Убрал

2024-09-22 16:45 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Program.cs
> +}
+

2024-09-22 16:45 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Program.cs
> +        Host.CreateDefaultBuilder(args)
+

2024-09-22 16:52 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Startup.cs
> +    /// </remarks>
Убрал

2024-09-22 16:55 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Interfaces/IEventService.cs
> +    /// Interface for working with event generator.
Для работы с событиями. Поправил

2024-09-22 16:55 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Interfaces/IEventService.cs
> +        EventDto CreateEvent(Guid generatorpId);
done

2024-09-22 16:59 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Interfaces/IEventService.cs
> +        /// Create a event.
done

2024-09-22 17:01 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Services/EventService.cs
> +    /// Class for working with event generator servisce.
done

2024-09-22 17:20 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Models/EventResponse.cs
> +        public int EventCoint { get; set; }
Обсудили, переименовал в EventLevel, который буде передавать в контроллер корабля

2024-09-22 17:20 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/Models/GeneratorResponse.cs
> +        public int Troublecoint { get; set; }
Переименовал в TroubleCoin

2024-09-28 10:10 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator/appsettings.Development.json
У меня показывается, обсудим на встрече.

2024-09-28 10:50 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Mappers/EventMapper.cs
> +    /// Mappers for events generator models.
поправил

2024-09-28 10:51 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/Event/EventDto.cs
> +        public int EventCoint { get; set; }
перделал на EventLevel, как обсуждали

2024-09-28 10:51 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/Generator/GeneratorDto.cs
> +        public int Troublecoint { get; set; }
поправил

2024-09-28 11:04 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/Generator/GetGeneratorDto.cs
Удалил

2024-09-28 11:05 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/NewDayMessadeDto.cs
поправил

2024-09-28 19:33 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +        /// Const.
Поправил наименование константы и описание

2024-09-28 19:33 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +        private const int TroublecointStart = 10;
Исправил

2024-09-28 19:33 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/EventDBContext.cs
> +            optionsBuilder.UseNpgsql(config.GetConnectionString("DefaultConnection"));
С консумером добавлю

2024-09-28 19:34 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/EventDBContext.cs
> +        }
Убрал

2024-09-28 19:35 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
> +        public Guid GenertatorId { get; set; }
Исправил

2024-09-28 19:35 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
> +        public int EventCoint { get; set; }
Исправил

2024-09-28 19:37 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
> +        /// Genertator ID.
Исправил

2024-09-28 19:37 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Generator.cs
> +        public int Troublecoint { get; set; }
Исправил

2024-09-28 19:43 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
> +    public class Event : BaseEntity
Убрал

2024-09-28 19:43 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Generator.cs
> +    public class Generator : BaseEntity
Убрал

2024-09-28 19:43 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/Event/CreateEventDto.cs
> +        public int EventCoint { get; set; }
Поправил

2024-09-28 19:45 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +            Generator generator = _generatorRepository.Get(shipId);
Пименял на generatorId

2024-09-29 17:05 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Models/NewDayMessadeDto.cs
> +        public Guid ShipId { get; set; }
Поправил

2024-09-29 17:05 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +    /// Class for working with event generator servisce.
Поправил

2024-09-29 17:05 UTC, tmpbx29 commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
> +        [Column("genertator_id")]
Поправил

2024-09-29 23:39 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Helpers/GuidGenerator.cs
Добавила недостающий пакет (stylecop).
Скопировала свежайший .editorconfig из GameController.

2024-09-29 23:39 UTC, Eclyocy commented on ProblemGenerator/.editorconfig
Добавила недостающий stylecop.

2024-09-29 23:40 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Repository/BaseRepository.cs
Без update было не справиться, т.к. нужно было выдавать монетки.
Delete нужно будет добавить позднее.

2024-09-29 23:40 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Services/EventService.cs
> +            createEventDto.troublecoint = random.Next(0, 10);
Добавила отдельный ендпоинт для начисления (одной) монетки.
Можно будет перелезть с этого ендпоинта на обработчик события из очереди.

2024-09-29 23:42 UTC, Eclyocy commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
Поправила пути.
Схему мвп не правила.
![image](https://github.com/user-attachments/assets/1498b838-df04-43dc-9ffb-52bd477a70e0)

2024-09-29 23:44 UTC, Eclyocy commented on ProblemGenerator/EventGenerator/Controllers/EventGeneratorController.cs
> +        public async Task<EventResponse> CreateEvent(Guid shipId)
Структура файлов устарела.
https://github.com/Eclyocy/otus-space/blob/ea79f3cc63f431d84c94115434a34d4c3f3f9c2c/EventGenerator/EventGenerator/Controllers/GeneratorController.cs
Контроллер генераторов.

2024-09-29 23:44 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Ship.cs
Таблица ликвидирована.

2024-09-29 23:46 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Event.cs
Генератор: https://github.com/Eclyocy/otus-space/blob/ea79f3cc63f431d84c94115434a34d4c3f3f9c2c/EventGenerator/EventGenerator.Database/Models/Generator.cs
Ивенты: https://github.com/Eclyocy/otus-space/blob/ea79f3cc63f431d84c94115434a34d4c3f3f9c2c/EventGenerator/EventGenerator.Database/Models/Event.cs
У проблемы теперь есть "уровень" крутости. Сколько она стоила -- неважно, хотя это и совпадает с енумом. На выход (REST) подаётся string.

2024-09-29 23:46 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Models/Event/CreateEventDto.cs
Упростила модельки.

2024-09-29 23:47 UTC, Eclyocy commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        /// Заглушка - Получение Guid корабля.
Пофиксила.

2024-09-29 23:47 UTC, Eclyocy commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        [Route("{shipId}")]
Поправила все пути.

2024-09-29 23:48 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Элементы решения", "Элементы решения", "{D3364EA2-1B82-4683-A5A3-1C44747150EA}"
Переименовала.

2024-09-29 23:49 UTC, Eclyocy commented on ProblemGenerator/EventGenerator/Controllers/GeneratorController.cs
> +        public CreateGeneratorRequest GetShip()
Перенесла в TestController, навесила [Outdated].

2024-09-29 23:53 UTC, Eclyocy commented on ProblemGenerator/EventGenerator/appsettings.Development.json
Так и не показывается, не обсудили.
Думаю, можно отложить, есть более приоритетные дела.

2024-09-29 23:54 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Services/EventService.cs
> +            IGeneratorRepository generatorRepository,
Исправила.

2024-09-29 23:54 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Models/Event/EventDto.cs
> +        public int EventCoint { get; set; }
Поменяла на enum.

2024-09-29 23:54 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Services/Models/Generator/GeneratorDto.cs
> +        public int Troublecoint { get; set; }
Расписала в сервисе.

2024-09-29 23:56 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/EventDBContext.cs
> +            optionsBuilder.UseNpgsql(config.GetConnectionString("DefaultConnection"));
Исправила докерфайл, добавила докер-композ, прописала переменные окружения.

2024-09-29 23:56 UTC, Eclyocy commented on ProblemGenerator/EventGenerator.Database/EventGenerator.Database/Models/Generator.cs
> +    }
Добавила.

2024-09-30 07:13 UTC, Eclyocy approved these changes

2024-09-30 15:11 UTC, dm-demin approved these changes

2024-09-30 15:17 UTC, merged