Feature/game controller authorization for actual main
Eclyocy/otus-space pull request #35
Opened 2024-10-10 13:25 UTC by SergeyZdanov

При авторизации берется юзер из бд, для этого сделал поиск юзера по логину. 
Пароль теперь хешируются при создание нового юзера. 
Сравниваются пароли тоже по хешу.

2024-10-17 18:16 UTC, Eclyocy requested changes

2024-10-17 18:16 UTC, Eclyocy commented on GameController/GameController.Services/Services/UserService.cs
> +        private bool GetRepositoryUserByName(string name, string password)
![auth_service](https://github.com/user-attachments/assets/f51351f3-c883-4e5e-a9a2-16f4bd1c4be3)

2024-10-17 18:16 UTC, Eclyocy commented on GameController/GameController.API/Models/Auth/LoginModel.cs
Обсудили, что модели на слое контроллера -- либо ...Request, либо ...Response, и слой сервисов получает свои с постфиксом Dto.

2024-10-17 18:16 UTC, Eclyocy commented on GameController/GameController.API/Properties/appsettings.json
Убрать отсюда и из .csproj

2024-10-20 10:54 UTC, dm-demin commented on GameController/GameController.API/Controllers/AuthController.cs
> +                var (token, refreshToken, expiresIn) = _jwtService.GenerateTokens(login.Username);
Мне кажется есть смысл создавать токе на id пользователя. Имя наверное можно и менять, но если мы зпрещаем менять имя - ок. Было бы удобнее при отправке уведомлений, но не критично.

2024-11-03 14:19 UTC, closed without merging