Add UnitTest
Eclyocy/otus-space pull request #36
Opened 2024-10-13 17:36 UTC by tmpbx29

Добавил проект с UnitTests. 
Обернул тестами все действия, что есть в сервисе, кроме AddTroubleCoin.
Сделал на примере UnitTests из GameController

2024-10-17 18:32 UTC, Eclyocy requested changes

2024-10-17 18:32 UTC, Eclyocy commented on EventGenerator/EventGenerator.Tests/GeneratorServiceTest.cs
> +        private EventService _eventService;
Поле _eventService -- лишнее.
Сервис генератора зависит от IGeneratorRepository, IEventService, ILogger<GeneratorService> и IMapper.
Все эти зависимости (и только их) нужно замокать.

2024-10-17 18:32 UTC, Eclyocy commented on EventGenerator/EventGenerator.Tests/GeneratorServiceTest.cs
> +        public void CreateGenerator_ReturnGeneratorDto_WhenGeneratorСorrect()
В названии метода есть кириллическая "С".

2024-10-17 18:32 UTC, Eclyocy commented on EventGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +            _logger.LogInformation("Get events by the generator {generatorId}.", generatorId);
Откатить.

2024-10-17 18:32 UTC, Eclyocy commented on EventGenerator/EventGenerator.Services/Mappers/GeneratorMapper.cs
> +                .ForMember(x => x.ShipId, opt => opt.MapFrom(x => x.Id));
Откатить.

2024-10-17 18:32 UTC, Eclyocy commented on EventGenerator/EventGenerator.Database/Repository/EventRepository.cs
> +        #region public methods
Непонятно, почему в PR про тесты меняется логика репозитория, -- откатить.

2024-10-17 18:32 UTC, Eclyocy commented on EventGenerator/EventGenerator.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "EventGenerator.Tests", "EventGenerator.Tests\EventGenerator.Tests.csproj", "{1172E32E-F044-4628-9FEB-19A13BE39F4E}"
Наверное, докер-файл тоже нужно поправить.

2024-10-17 18:55 UTC, tmpbx29 commented on EventGenerator/EventGenerator.Tests/GeneratorServiceTest.cs
> +        public void CreateGenerator_ReturnGeneratorDto_WhenGeneratorСorrect()
Поправил

2024-10-17 18:56 UTC, tmpbx29 commented on EventGenerator/EventGenerator.Services/Services/GeneratorService.cs
> +            _logger.LogInformation("Get events by the generator {generatorId}.", generatorId);
Откатил

2024-10-17 18:56 UTC, tmpbx29 commented on EventGenerator/EventGenerator.Services/Mappers/GeneratorMapper.cs
> +                .ForMember(x => x.ShipId, opt => opt.MapFrom(x => x.Id));
Откатил

2024-10-17 19:01 UTC, tmpbx29 commented on EventGenerator/EventGenerator.Tests/GeneratorServiceTest.cs
> +        private EventService _eventService;
_eventService используется в GetEvents_WhenGeneratorIdIsValid() и GetGeneratorEvents_WhenGeneratorIdIsInvalid()

2024-10-17 19:26 UTC, tmpbx29 commented on EventGenerator/EventGenerator.Database/Repository/EventRepository.cs
> +        #region public methods
Небыло ни одного метода, который возвращает  List<Event>

2024-10-17 19:28 UTC, tmpbx29 commented on EventGenerator/EventGenerator.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "EventGenerator.Tests", "EventGenerator.Tests\EventGenerator.Tests.csproj", "{1172E32E-F044-4628-9FEB-19A13BE39F4E}"
Поправил

2024-10-18 17:22 UTC, Eclyocy commented on EventGenerator/EventGenerator.Database/Repository/EventRepository.cs
> +        #region public methods
Понятнее не становится, что ты имеешь в виду?

2024-10-18 17:23 UTC, Eclyocy commented on EventGenerator/EventGenerator.Tests/EventServiceTest.cs
> +            _mapperMock = new Mock<IMapper>();
Тест падает, т.к. модельку неправильно заполняешь.
Давай попробуем использовать настоящий маппер, -- пример можно посмотреть в тестах для SpaceShip.

2024-11-07 15:21 UTC, Eclyocy approved these changes

2024-11-09 17:50 UTC, tmpbx29 reviewed
LGTM

2024-11-09 17:52 UTC, merged