Базовый веб сервис корабля
Eclyocy/otus-space pull request #9
Opened 2024-07-09 05:41 UTC by dm-demin

[Spaceship]
Добавлен базовый контроллер для работы с кораблем
Базовая структура без подключения к модели и репозиторию
Добавлена примитивная работа с RabbitMQ
Сервис заглушка для создания корабля:
- выдача рандомного Guid при создании корабля
- выдача статичного ответа для метрик на запрошенный Id

Еще не сделано:
- нужно будет вынести в отдельный провайдер подключение с инфраструктурой
- разобраться с сертификатами для сервиса корабля, сейчас доступ по http

[Docker]
Добавлен сервис корабля в общий docker-compose

2024-07-09 07:05 UTC, Eclyocy commented
Нужно добавить в solution .editorconfig из GameController (https://github.com/Eclyocy/otus-space/blob/main/GameController/.editorconfig) и починить все ошибки код-стиля.

2024-07-09 07:46 UTC, Eclyocy requested changes

2024-07-09 07:46 UTC, Eclyocy commented on docker-compose.yml
> +    - RABBITMQ_STEP_QUEUE=steps
Если это та же очередь, в которую пишет GameController, то нужно использовать то же значение: q_new_day_ship.

2024-07-09 07:46 UTC, Eclyocy commented on docker-compose.yml
> +    - RABBITMQ_TROUBLES_QUEUE=troubles
Лучше именовать очереди единообразно: q_troubles

2024-07-09 07:46 UTC, Eclyocy commented on docker-compose.yml
> +    image: webapi
"webapi" слишком общее название.
А ещё не хватает директивы container_name.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/docker-compose.debug.yml
Нужен ли этот файл?

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/docker-compose.yml
Нужен ли этот файл?

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Contracts/MessageDTO.cs
> +    public Guid Id {get;set;}
Из кода будет выглядеть, как Id сообщения.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/mock/MockSpaceShip.Service/MockSpaceShipService.cs
> +
Слишком много пустых строк.
Применимо ко многим файлам.
Добавила общий комментарий про .editorconfig.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Contracts/MessageDTO.cs
> +}
Нет пустой строки в конце файла.
Применимо ко многим файлам.
Добавила общий комментарий про .editorconfig.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +    namespace SpaceShip.Service.Contracts;
Неверная табуляция.
Лишняя пустая строка в начале.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        /// Наименованеи ресурса
Опечатка, "Наименование".

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        public string ? Name { get; set; }
Почему вопрос отдельно от типа?

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        /// Состояние ресурса (спит, норма, проблема)
Вероятно, нужно использовать enum?

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Models/Ship.cs
> +public class Ship
По моим воспоминаниям договорились модели уровня сервисов именовать с постфиксом Dto.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Models/Resorce.cs
Файл и класс должны наименоваться "Resource", а точнее "ResourceDto".

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Models/ResourceState.cs
Файл и класс должны наименоваться "ResourceState", а точнее "ResourceStateDto".

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
> +    public SpaceShipDTO CreateShip() // <--- Тупо отдать ID или всю структуру?
Отдавать в любом случае модель.
На уровне сервисов лучше отдавать SpaceShipDto.
Пускай контроллер разбирается, что именно отдавать клиенту.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/WebAPI/Controllers/SpaceShipController.cs
Кажется, что директория тоже должна называться "SpaceShip.WebAPI", а не просто WebAPI.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/WebAPI/Settings/RabbitMQSettings.cs
> +#pragma warning disable CS1591
Это зачем?

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/WebAPI/Program.cs
> +
Нет namespace.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/WebAPI/Program.cs
> +using System.Runtime.CompilerServices;
Не отсортированы usings. См. комментарий про .editorconfig.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/WebAPI/Settings/SettingsBase.cs
> +public class SettingsBase
Кажется, что это не SettingsBase, а какой-то хелпер для чтения переменных из ENV.
Не вполне понятно, зачем от него наследоваться.

2024-07-09 07:46 UTC, Eclyocy commented on SpaceShip/src/SpaseShip.Service.EventsProvider/Services/StepEventProvider.cs
> +            _logger.LogInformation("[GameStepProvider] Received new message: {message}",message);
Кажется, что префикс "[GameStepProvider]" нужно улучшить.
Если подразумевалось название класса, то дублировать его здесь не нужно (к тому же в таких случаях лучше использовать nameof(), иначе может произойти переименование класса, а строковые константы об этом не узнают).

Можно подсмотреть вот здесь: https://github.com/Eclyocy/otus-space/blob/main/GameController/GameController.API/Helpers/CustomConsoleFormatter.cs

2024-07-09 15:32 UTC, dm-demin commented on docker-compose.yml
> +    - RABBITMQ_HOST=rabbitmq-otus
Хороший вопрос, но ниже определён контейнер rabbitmq с hostame = rabbitmq-otus

2024-07-09 16:26 UTC, dm-demin commented on SpaceShip/src/SpaseShip.Service.EventsProvider/Services/StepEventProvider.cs
> +            _logger.LogInformation("[GameStepProvider] Received new message: {message}",message);
Логирование в планах. Сейчас форматирование не подключено.

2024-07-09 16:27 UTC, dm-demin commented on SpaceShip/src/WebAPI/Program.cs
> +
Нужен ли он для оператра вехнего уровня, могу переключить к виду с Main

https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/program-structure/top-level-statements

2024-07-09 16:27 UTC, dm-demin commented on SpaceShip/src/WebAPI/Settings/RabbitMQSettings.cs
> +#pragma warning disable CS1591
Отключить предупреждение о XML комментариях, наверное есть смысл перенести в настройки проекта

2024-07-09 16:34 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        /// Состояние ресурса (спит, норма, проблема)
Временно, насколько помню, хотели выводить в отдельную общую библиотеку типы и состояния ресурсов. Нужно и тут вводить модель DTO?

2024-07-09 19:05 UTC, dm-demin commented on .vscode/launch.json
есть, нужно понять почему не работает

2024-07-09 19:05 UTC, dm-demin commented on docker-compose.yml
> +    - RABBITMQ_STEP_QUEUE=steps
исправил

2024-07-09 19:05 UTC, dm-demin commented on docker-compose.yml
> +    image: webapi
исправил

2024-07-09 19:06 UTC, dm-demin commented on SpaceShip/docker-compose.debug.yml
убрал

2024-07-09 19:06 UTC, dm-demin commented on SpaceShip/docker-compose.yml
убрал, скорее для локальной отладки

2024-07-09 19:06 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/MessageDTO.cs
> +    public Guid Id {get;set;}
исправил

2024-07-09 19:06 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/MessageDTO.cs
> +}
исправил

2024-07-09 19:11 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        /// Наименованеи ресурса
исправил

2024-07-09 19:11 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +    namespace SpaceShip.Service.Contracts;
исправил

2024-07-09 19:11 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        public string ? Name { get; set; }
исправил

2024-07-09 19:12 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Contracts/ResourceDTO.cs
> +        /// Состояние ресурса (спит, норма, проблема)
Еще нужно настроить отображение Enum в Swagger

2024-07-09 19:12 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Models/Ship.cs
> +public class Ship
удалил эти модели, должны быть в части работы с БД

2024-07-09 19:12 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Models/Resorce.cs
исправил

2024-07-09 19:12 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Models/ResourceState.cs
исправил

2024-07-09 19:13 UTC, dm-demin commented on SpaceShip/src/WebAPI/Controllers/SpaceShipController.cs
исправил

2024-07-09 19:13 UTC, dm-demin commented on SpaceShip/src/WebAPI/Settings/SettingsBase.cs
> +public class SettingsBase
убрал пока эти кассы

2024-07-10 19:34 UTC, dm-demin commented on .vscode/launch.json
исправлено

2024-07-10 19:34 UTC, dm-demin commented on .vscode/settings.json
исправлено

2024-07-10 19:34 UTC, dm-demin commented on .vscode/tasks.json
исправлено

2024-07-10 19:34 UTC, dm-demin commented on docker-compose.yml
> +    - RABBITMQ_HOST=rabbitmq-otus
исправлено

2024-07-10 19:35 UTC, dm-demin commented on docker-compose.yml
> +    - RABBITMQ_TROUBLES_QUEUE=troubles
исправлено

2024-07-10 19:35 UTC, dm-demin commented on SpaceShip/mock/MockSpaceShip.Service/MockSpaceShipService.cs
> +
исправлено

2024-07-10 19:35 UTC, dm-demin commented on SpaceShip/src/SpaceShip.Service/Services/SpaceShipService.cs
> +    public SpaceShipDTO CreateShip() // <--- Тупо отдать ID или всю структуру?
исправлено

2024-07-10 19:36 UTC, dm-demin commented on SpaceShip/src/WebAPI/Program.cs
> +using System.Runtime.CompilerServices;
исправлено

2024-07-10 19:36 UTC, dm-demin commented
Поправил замечания.

2024-07-11 16:27 UTC, Eclyocy approved these changes

2024-07-11 16:33 UTC, merged